<b>Consider the below code to answer further questions:</b>


<b>import numpy as np                                                                                                           
list_ = [ '1' , '2', '3' , '4' , '5' ]                                                                                           
array_list = np.array(object = list_)</b>

<b>Q1. Is there any difference in the data type of variables list_ and array_list?If there is then write a code to print the data types of both the variables.</b>

'Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list 
   is a NumPy array object.

In [6]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


<b>Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.</b>

In [9]:
# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


<b>Q3. Considering the following changes in the variable, array_list:                                                           
array_list = np.array(object = list_, dtype = int)</b>

In [10]:
array_list = np.array(object = list_ , dtype = int)
for element in list_:
    print(type(element))
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


<b>Consider the below code to answer further questions:</b>

<b>import numpy as np                                                                                                           
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]                                                                                     
num_array = np.array(object = num_list)</b>

<b>Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape (ii) size</b>

In [12]:
# Print the shape of num_array
print(num_array.shape)

# Print the size of num_array
print(num_array.size)

(2, 3)
6


<b>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.</b>

In [13]:
zeros_matrix = np.zeros((3,3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<b>Q6. Create an identity matrix of shape (5,5) using numpy functions?</b>

In [14]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
